# Copyright 2019 ConsenSys AG.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Project information
site_name: "Tessera"
site_url: https://docs.tessera.consensys.net/
site_description: Tessera is an open-source private transaction manager developed under the Apache 2.0 license and written in Java.
site_author: Tessera community
copyright: Tessera is licensed under Apache 2.0 License /
  This documentation is maintained by <a href="https://consensys.net/">ConsenSys</a>.

#extra project info and template customisation
extra:
  logo_is_text: true
  latest_version_warning:
    url_contains: /latest/
    text: 'You are reading GoQuorum development version documentation and
    some displayed features may not be available in the stable release.
    You can switch to stable version using the version box at screen bottom.'
  support:
    company: ConsenSys
    tool: Slack
    faq: https://consensys.net/quorum/faq
    channel: https://93ecjxb0d3.execute-api.us-east-1.amazonaws.com/Express/
    email: quorum@consensys.net
    website: https://consensys.net/
    issues: https://github.com/ConsenSys/tessera/issues
  google:
    site_verification: 'VL2MgMm7Gj-fEOH3SkAuP4eXOY7rIShFFbTI5RktuA0'
    tag_manager: 'GTM-N4VQ49H'
  inverted_logo: 'images/inverted_logo.svg'

# Software Repository
repo_name: Consensys/tessera
repo_url: https://github.com/ConsenSys/tessera.git

theme:
  name: material
  custom_dir: common/custom_theme
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'en'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.svg'

nav:
  - How to:
    - Generate keys: HowTo/Generate-keys.md
    - Configure:
      - Tessera: HowTo/Configure/Tessera.md
      - Transaction manager: HowTo/Configure/Transaction-manager.md
      - Enclave: HowTo/Configure/Enclave.md
      - Keys: HowTo/Configure/Keys.md
      - TLS: HowTo/Configure/TLS.md
      - Key vault:
         - Hashicorp Vault: HowTo/Configure/KeyVault/Hashicorp-Vault.md
         - AWS Secrets Manager: HowTo/Configure/KeyVault/AWS-Secrets-Manager.md
         - Azure Key Vault: HowTo/Configure/KeyVault/Azure-Key-Vault.md
      - Override configuration file: HowTo/Configure/Override-config.md
    - Use:
      - Monitoring: HowTo/Use/Monitoring.md
      - Logging: HowTo/Use/Logging.md
    - Migrate from Constellation: HowTo/MigrateFromConstellation.md
  - Tutorials:
      - Quorum Developer Quickstart: Tutorials/Quorum-Dev-Quickstart.md
  - Concepts:
    - Transaction manager: Concepts/Transaction-manager.md
    - Enclave: Concepts/Enclave.md
    - Enclave types: Concepts/Enclave-types.md
    - Node Discovery: Concepts/p2p-discovery.md
  - Reference:
    - Configuration file: Reference/SampleConfiguration.md
    - Bootstrap node configuration file: Reference/BootstrapSampleConfiguration.md
    - REST API Methods: Reference/REST-API.md

markdown_extensions:
  - toc:
      permalink: 
      toc_depth: 3
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - abbr
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - smarty
  - attr_list
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

plugins:
  - search:
      lang: 'en'
      separator: '[\s]+'
  - markdownextradata
  - redirects:
      redirect_maps:
        # Configure redirects using key:value pairs:
        # old_path.md: new_path.md
        # you can't use an already redirected path as an old_path.
        # new_path can be a file inside the docs/ folder or any URL (http://...)
